# Generated by Django 5.1.6 on 2025-02-28 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_remove_useract_reminder_access_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useract',
            name='last_login_at',
        ),
        migrations.RemoveField(
            model_name='useract',
            name='login_count',
        ),
        migrations.RemoveField(
            model_name='useract',
            name='notes_access_count',
        ),
        migrations.AddField(
            model_name='useract',
            name='activity_type',
            field=models.CharField(default='default_value', max_length=50),
        ),
        migrations.AlterField(
            model_name='useract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.user'),
        ),
    ]
