# Generated by Django 5.1.6 on 2025-02-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_remove_useract_last_login_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useract',
            name='activity_type',
            field=models.CharField(max_length=50),
        ),
    ]
